name: sparta-delivery
services:
  postgres:
    image: postgres:16.6
    container_name: sparta-delivery-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-delivery}
      POSTGRES_USER: ${DB_USERNAME:-delivery_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-delivery_password}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USERNAME::-delivery-user} -d $${DB_NAME:-delivery}"]
      interval: 5s # test 속도
      timeout: 5s
      retries: 5

# 실제 운영 테스트에서는 볼륨이 필요 없습니다.
volumes:
  postgres_data:
